#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "digipad"
name = "Digipad"

description.en = "Create multimedia collaborative walls"
description.fr = "Créer des murs collaboratifs multimédias"

version = "1.5.14~ynh1"

maintainers = ["mrflos"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://digipad.app/"
demo = "https://digipad.app/"
admindoc = "https://codeberg.org/ladigitale/digipad/src/branch/master/README.md"
code = "https://codeberg.org/ladigitale/digipad"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap =  false
sso = false

disk = "800M"
ram.build = "1000M"
ram.runtime = "300M"

[install]

    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.authprovider]
    type = "select"
    choices = ["yeswiki", "baserow"]
      
    [install.password]
    help.en = "Password to access the administration page `/admin`"
    help.fr ="Mot de passe pour accéder à la page d'administration `/admin`"
    type = "password"

    [install.wiki_admin_password]
    ask.en = "Wiki admin password"
    ask.fr = "Mot de passe de l'administrateur du wiki"
    type = "password"
    visible = "authprovider == 'YesWiki'"
    #visible = "authprovider == 'yeswiki'"

    [install.create_account]
    ask.en = "Allow account creation"
    ask.fr = "Autoriser la création de comptes"
    type = "boolean"
    default = 1
    
    [install.account_validation]
    ask.en = "Email registration validation"
    ask.fr = "Validation de l'inscription par email"
    type = "boolean"
    default = 1

    [install.without_account]
    ask.en = "Allow pad creation without account"
    ask.fr = "Autoriser la création de pads sans compte"
    type = "boolean"
    default = 1

    [install.pad_limit]
    ask.en = "Maximum number of pads per user"
    ask.fr = "Nombre maximum de pads par compte utilisateur"
    type = "number"
    default = 50
    min = 0
    max = 1000

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://codeberg.org/ladigitale/digipad/archive/1.5.14.tar.gz"
    sha256 = "b8d3ca1274933034ce4e854351d61bc19489b31b4f7abbaddef8a9dd8ea335bb"
    autoupdate.strategy = "latest_forgejo_tag"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "postgresql, postgresql-contrib, redis-server, libreoffice, ghostscript, graphicsmagick, build-essential"

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "24"
